add triger event push another branch

diff --git a/gitlab-ci.yml b/gitlab-ci.yml
--- a/gitlab-ci.yml
+++ b/gitlab-ci.yml
@@ -1,5 +1,10 @@
 variables:
   GIT_CLONE_PATH: $CI_BUILDS_DIR
+  GIT_SUBMODULE_STRATEGY: recursive
+
+before_script:
+  - git submodule sync --recursive
+  - git submodule update --init --recursive
 
 cache:
     key:
@@ -27,14 +32,15 @@ build:
       paths:
         - dist/
     before_script:   
-        - pwd && cd $CI_BUILDS_DIR        
+        - pwd && cd $CI_BUILDS_DIR     
+        - npm config set registry https://registry.npmjs.org/    
         - npm ci --cache .npm --prefer-offline
         - ansible-playbook -i hosts playbook/playbook.yml --syntax-check
         - ansible-playbook -i hosts playbook/playbook.yml 
 
     rules:
       - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
-      - if: '$CI_COMMIT_BRANCH == "master"'
+      - if: '$CI_COMMIT_BRANCH == "development"'
         when: on_success          
         allow_failure: true
       - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^src/ && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
@@ -46,7 +52,8 @@ build:
       - if: '$CI_COMMIT_TAG != ""'       
 
     script: 
-        - pwd && cd $CI_BUILDS_DIR     
+        - pwd && cd $CI_BUILDS_DIR   
+        - "curl -X POST -F token=5c4f7855e3dbd29f75f60ff716bf85 -F ref=development https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/trigger/pipeline"  
         - ./node_modules/@angular/cli/bin/ng build --prod --base-href /development/     
 
     retry:
@@ -70,6 +77,7 @@ test:
 
     only:
         - master
+        - development
 
     allow_failure: true
 
@@ -109,12 +117,14 @@ archive:
             unzip *.zip -d $DIR_RELEASE/web_app/; 
           else 
             echo "Preparing Archive package...";
-            cd $CI_BUILDS_DIR && pwd
-            zip -r development.zip dist/material-app && cp -r development.zip $DIR_RELEASE/web_app/            
+            cd $CI_BUILDS_DIR && pwd               
+            curl -L --progress-bar --header "PRIVATE-TOKEN: 9SRJZxic2k7ex57649sp" "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/master/download?job=build" -o $DIR_RELEASE/web_app/artifacts.zip 2>&1;
+            chmod -Rv 775 $DIR_RELEASE/web_app/artifacts.zip 
             echo "Archiving Package success...!";
           fi   
     only:
-        - master    
+        - master 
+        - development   
 
     retry:
       max: 2
@@ -140,26 +150,46 @@ deploy:
             echo "Yes, file exists"; 
           else 
             echo "Compres Proses..."; 
-            tar -cf development_`date +%y_%m_%d`.tar.gz development; 
-            echo "compres success..."; 
-          fi
-        - tar -cf /var/www/html/development_`date +%y_%m_%d`.tar.gz /var/www/html/development
-        
+            if [[ ! -d "development" ]]
+            then
+                echo "Directory Not Found on your filesystem."
+            else
+                tar -cf /backup/web_app/development_`date +%y_%m_%d`.tar.gz development 
+                echo "compres success...";
+            fi             
+          fi                
+ 
     script: 
         - cd $DIR_RELEASE/web_app && pwd
         - echo "Extract Package...."
-        - unzip development.zip 
+        - |
+          if unzip *.zip 2>/dev/null; then
+            echo 'All is good, archive extracted' >&2;
+          else
+            echo 'Archive failed to extract' >&2;
+            rm -rf $DIR_RELEASE/web_app/artifacts.zip;
+            cd $CI_BUILDS_DIR && pwd;
+            zip -r artifacts.zip dist/material-app && mv artifacts.zip $DIR_RELEASE/web_app/;
+          echo "Archiving Package success...!";
+          fi 
+        - unzip artifacts.zip && ls -ltr node_modules      
+        - echo "Preparing remove packages web..."
+        - rm -rf /var/www/html/development 
+        - ls -ltr /var/www/html 
+        - echo "Remove Package Success..."
+        - mv dist/material-app /var/www/html/development 
+        - echo "Clean Up Package..."
+        - rm -rf *
+        - echo "Make Sure Privileges user.."
+        - ls -ltr /var/www/html/development
+        - chown -R appuser01:www-data /var/www/html/development && chmod -R 755 /var/www/html/development
+        - echo "Preparing restart service backend..."
+        - su appuser01 && cd /home/appuser01/sicepat_api && pm2 status app
+        - pm2 reload app && pm2 status app
         - echo "deploy Success.."
-        #- echo "Preparing remove packages web..."
-        #- rm -rf /var/www/html/development 
-        #- ls -ltr /var/www/html 
-        #- echo "Remove Package Success..."
-        #- mv dist/material-app /var/www/html/development
-        #- echo "Make Sure Privileges user.."
-        #- ls -ltr /var/www/html/development
-        #- chown -Rv appuser01:www-data /var/www/html/development && chmod -Rv 755 /var/www/html/development
     only:
         - master
+        - development
 
     retry:
       max: 2
@@ -170,6 +200,7 @@ deploy:
     start_in: 1 minutes
     after_script:
         - echo "Deploy development complete..."
+
     
 
 
